#
# This file is regenerated by t_audio.awk
# If you add/remove tests or change testnames, run
#  make -f Makefile.t_audio
#

# Call real test program, and then dispatch the result for atf.
h_audio() {
	local testname=$1
	outmsg=`$(atf_get_srcdir)/audiotest -AR $testname`
	local retval=$?
	if [ "$retval" = "0" ]; then
		atf_pass
	elif [ "$retval" = "1" ]; then
		atf_fail "$outmsg"
	elif [ "$retval" = "2" ]; then
		atf_skip "$outmsg"
	else
		atf_fail "unknown error $retval"
	fi
}

atf_test_case open_mode_RDONLY
open_mode_RDONLY_head() { }
open_mode_RDONLY_body() { h_audio open_mode_RDONLY }

atf_test_case open_mode_WRONLY
open_mode_WRONLY_head() { }
open_mode_WRONLY_body() { h_audio open_mode_WRONLY }

atf_test_case open_mode_RDWR
open_mode_RDWR_head() { }
open_mode_RDWR_body() { h_audio open_mode_RDWR }

atf_test_case open_audio_RDONLY
open_audio_RDONLY_head() { }
open_audio_RDONLY_body() { h_audio open_audio_RDONLY }

atf_test_case open_audio_WRONLY
open_audio_WRONLY_head() { }
open_audio_WRONLY_body() { h_audio open_audio_WRONLY }

atf_test_case open_audio_RDWR
open_audio_RDWR_head() { }
open_audio_RDWR_body() { h_audio open_audio_RDWR }

atf_test_case open_sound_RDONLY
open_sound_RDONLY_head() { }
open_sound_RDONLY_body() { h_audio open_sound_RDONLY }

atf_test_case open_sound_WRONLY
open_sound_WRONLY_head() { }
open_sound_WRONLY_body() { h_audio open_sound_WRONLY }

atf_test_case open_sound_RDWR
open_sound_RDWR_head() { }
open_sound_RDWR_body() { h_audio open_sound_RDWR }

atf_test_case open_sound_sticky
open_sound_sticky_head() { }
open_sound_sticky_body() { h_audio open_sound_sticky }

atf_test_case open_simul_RDONLY_RDONLY
open_simul_RDONLY_RDONLY_head() { }
open_simul_RDONLY_RDONLY_body() { h_audio open_simul_RDONLY_RDONLY }

atf_test_case open_simul_RDONLY_WRONLY
open_simul_RDONLY_WRONLY_head() { }
open_simul_RDONLY_WRONLY_body() { h_audio open_simul_RDONLY_WRONLY }

atf_test_case open_simul_RDONLY_RDWR
open_simul_RDONLY_RDWR_head() { }
open_simul_RDONLY_RDWR_body() { h_audio open_simul_RDONLY_RDWR }

atf_test_case open_simul_WRONLY_RDONLY
open_simul_WRONLY_RDONLY_head() { }
open_simul_WRONLY_RDONLY_body() { h_audio open_simul_WRONLY_RDONLY }

atf_test_case open_simul_WRONLY_WRONLY
open_simul_WRONLY_WRONLY_head() { }
open_simul_WRONLY_WRONLY_body() { h_audio open_simul_WRONLY_WRONLY }

atf_test_case open_simul_WRONLY_RDWR
open_simul_WRONLY_RDWR_head() { }
open_simul_WRONLY_RDWR_body() { h_audio open_simul_WRONLY_RDWR }

atf_test_case open_simul_RDWR_RDONLY
open_simul_RDWR_RDONLY_head() { }
open_simul_RDWR_RDONLY_body() { h_audio open_simul_RDWR_RDONLY }

atf_test_case open_simul_RDWR_WRONLY
open_simul_RDWR_WRONLY_head() { }
open_simul_RDWR_WRONLY_body() { h_audio open_simul_RDWR_WRONLY }

atf_test_case open_simul_RDWR_RDWR
open_simul_RDWR_RDWR_head() { }
open_simul_RDWR_RDWR_body() { h_audio open_simul_RDWR_RDWR }

atf_test_case open_multiuser_0
open_multiuser_0_head() { }
open_multiuser_0_body() { h_audio open_multiuser_0 }

atf_test_case open_multiuser_1
open_multiuser_1_head() { }
open_multiuser_1_body() { h_audio open_multiuser_1 }

atf_test_case write_PLAY_ALL
write_PLAY_ALL_head() { }
write_PLAY_ALL_body() { h_audio write_PLAY_ALL }

atf_test_case write_PLAY
write_PLAY_head() { }
write_PLAY_body() { h_audio write_PLAY }

atf_test_case read
read_head() { }
read_body() { h_audio read }

atf_test_case rept_write
rept_write_head() { }
rept_write_body() { h_audio rept_write }

atf_test_case rept_read
rept_read_head() { }
rept_read_body() { h_audio rept_read }

atf_test_case rdwr_fallback_RDONLY
rdwr_fallback_RDONLY_head() { }
rdwr_fallback_RDONLY_body() { h_audio rdwr_fallback_RDONLY }

atf_test_case rdwr_fallback_WRONLY
rdwr_fallback_WRONLY_head() { }
rdwr_fallback_WRONLY_body() { h_audio rdwr_fallback_WRONLY }

atf_test_case rdwr_fallback_RDWR
rdwr_fallback_RDWR_head() { }
rdwr_fallback_RDWR_body() { h_audio rdwr_fallback_RDWR }

atf_test_case rdwr_two_RDONLY_RDONLY
rdwr_two_RDONLY_RDONLY_head() { }
rdwr_two_RDONLY_RDONLY_body() { h_audio rdwr_two_RDONLY_RDONLY }

atf_test_case rdwr_two_RDONLY_WRONLY
rdwr_two_RDONLY_WRONLY_head() { }
rdwr_two_RDONLY_WRONLY_body() { h_audio rdwr_two_RDONLY_WRONLY }

atf_test_case rdwr_two_RDONLY_RDWR
rdwr_two_RDONLY_RDWR_head() { }
rdwr_two_RDONLY_RDWR_body() { h_audio rdwr_two_RDONLY_RDWR }

atf_test_case rdwr_two_WRONLY_RDONLY
rdwr_two_WRONLY_RDONLY_head() { }
rdwr_two_WRONLY_RDONLY_body() { h_audio rdwr_two_WRONLY_RDONLY }

atf_test_case rdwr_two_WRONLY_WRONLY
rdwr_two_WRONLY_WRONLY_head() { }
rdwr_two_WRONLY_WRONLY_body() { h_audio rdwr_two_WRONLY_WRONLY }

atf_test_case rdwr_two_WRONLY_RDWR
rdwr_two_WRONLY_RDWR_head() { }
rdwr_two_WRONLY_RDWR_body() { h_audio rdwr_two_WRONLY_RDWR }

atf_test_case rdwr_two_RDWR_RDONLY
rdwr_two_RDWR_RDONLY_head() { }
rdwr_two_RDWR_RDONLY_body() { h_audio rdwr_two_RDWR_RDONLY }

atf_test_case rdwr_two_RDWR_WRONLY
rdwr_two_RDWR_WRONLY_head() { }
rdwr_two_RDWR_WRONLY_body() { h_audio rdwr_two_RDWR_WRONLY }

atf_test_case rdwr_two_RDWR_RDWR
rdwr_two_RDWR_RDWR_head() { }
rdwr_two_RDWR_RDWR_body() { h_audio rdwr_two_RDWR_RDWR }

atf_test_case rdwr_simul
rdwr_simul_head() { }
rdwr_simul_body() { h_audio rdwr_simul }

atf_test_case drain_incomplete
drain_incomplete_head() { }
drain_incomplete_body() { h_audio drain_incomplete }

atf_test_case drain_pause
drain_pause_head() { }
drain_pause_body() { h_audio drain_pause }

atf_test_case drain_onrec
drain_onrec_head() { }
drain_onrec_body() { h_audio drain_onrec }

atf_test_case mmap_mode_RDONLY_NONE
mmap_mode_RDONLY_NONE_head() { }
mmap_mode_RDONLY_NONE_body() { h_audio mmap_mode_RDONLY_NONE }

atf_test_case mmap_mode_RDONLY_READ
mmap_mode_RDONLY_READ_head() { }
mmap_mode_RDONLY_READ_body() { h_audio mmap_mode_RDONLY_READ }

atf_test_case mmap_mode_RDONLY_WRITE
mmap_mode_RDONLY_WRITE_head() { }
mmap_mode_RDONLY_WRITE_body() { h_audio mmap_mode_RDONLY_WRITE }

atf_test_case mmap_mode_RDONLY_READWRITE
mmap_mode_RDONLY_READWRITE_head() { }
mmap_mode_RDONLY_READWRITE_body() { h_audio mmap_mode_RDONLY_READWRITE }

atf_test_case mmap_mode_WRONLY_NONE
mmap_mode_WRONLY_NONE_head() { }
mmap_mode_WRONLY_NONE_body() { h_audio mmap_mode_WRONLY_NONE }

atf_test_case mmap_mode_WRONLY_READ
mmap_mode_WRONLY_READ_head() { }
mmap_mode_WRONLY_READ_body() { h_audio mmap_mode_WRONLY_READ }

atf_test_case mmap_mode_WRONLY_WRITE
mmap_mode_WRONLY_WRITE_head() { }
mmap_mode_WRONLY_WRITE_body() { h_audio mmap_mode_WRONLY_WRITE }

atf_test_case mmap_mode_WRONLY_READWRITE
mmap_mode_WRONLY_READWRITE_head() { }
mmap_mode_WRONLY_READWRITE_body() { h_audio mmap_mode_WRONLY_READWRITE }

atf_test_case mmap_mode_RDWR_NONE
mmap_mode_RDWR_NONE_head() { }
mmap_mode_RDWR_NONE_body() { h_audio mmap_mode_RDWR_NONE }

atf_test_case mmap_mode_RDWR_READ
mmap_mode_RDWR_READ_head() { }
mmap_mode_RDWR_READ_body() { h_audio mmap_mode_RDWR_READ }

atf_test_case mmap_mode_RDWR_WRITE
mmap_mode_RDWR_WRITE_head() { }
mmap_mode_RDWR_WRITE_body() { h_audio mmap_mode_RDWR_WRITE }

atf_test_case mmap_mode_RDWR_READWRITE
mmap_mode_RDWR_READWRITE_head() { }
mmap_mode_RDWR_READWRITE_body() { h_audio mmap_mode_RDWR_READWRITE }

atf_test_case mmap_len
mmap_len_head() { }
mmap_len_body() { h_audio mmap_len }

atf_test_case mmap_twice
mmap_twice_head() { }
mmap_twice_body() { h_audio mmap_twice }

atf_test_case mmap_multi
mmap_multi_head() { }
mmap_multi_body() { h_audio mmap_multi }

atf_test_case poll_mode_RDONLY_IN
poll_mode_RDONLY_IN_head() { }
poll_mode_RDONLY_IN_body() { h_audio poll_mode_RDONLY_IN }

atf_test_case poll_mode_RDONLY_OUT
poll_mode_RDONLY_OUT_head() { }
poll_mode_RDONLY_OUT_body() { h_audio poll_mode_RDONLY_OUT }

atf_test_case poll_mode_RDONLY_INOUT
poll_mode_RDONLY_INOUT_head() { }
poll_mode_RDONLY_INOUT_body() { h_audio poll_mode_RDONLY_INOUT }

atf_test_case poll_mode_WRONLY_IN
poll_mode_WRONLY_IN_head() { }
poll_mode_WRONLY_IN_body() { h_audio poll_mode_WRONLY_IN }

atf_test_case poll_mode_WRONLY_OUT
poll_mode_WRONLY_OUT_head() { }
poll_mode_WRONLY_OUT_body() { h_audio poll_mode_WRONLY_OUT }

atf_test_case poll_mode_WRONLY_INOUT
poll_mode_WRONLY_INOUT_head() { }
poll_mode_WRONLY_INOUT_body() { h_audio poll_mode_WRONLY_INOUT }

atf_test_case poll_mode_RDWR_IN
poll_mode_RDWR_IN_head() { }
poll_mode_RDWR_IN_body() { h_audio poll_mode_RDWR_IN }

atf_test_case poll_mode_RDWR_OUT
poll_mode_RDWR_OUT_head() { }
poll_mode_RDWR_OUT_body() { h_audio poll_mode_RDWR_OUT }

atf_test_case poll_mode_RDWR_INOUT
poll_mode_RDWR_INOUT_head() { }
poll_mode_RDWR_INOUT_body() { h_audio poll_mode_RDWR_INOUT }

atf_test_case poll_out_empty
poll_out_empty_head() { }
poll_out_empty_body() { h_audio poll_out_empty }

atf_test_case poll_out_full
poll_out_full_head() { }
poll_out_full_body() { h_audio poll_out_full }

atf_test_case poll_out_hiwat
poll_out_hiwat_head() { }
poll_out_hiwat_body() { h_audio poll_out_hiwat }

atf_test_case poll_out_unpause
poll_out_unpause_head() { }
poll_out_unpause_body() { h_audio poll_out_unpause }

atf_test_case poll_out_simul
poll_out_simul_head() { }
poll_out_simul_body() { h_audio poll_out_simul }

atf_test_case poll_in_simul
poll_in_simul_head() { }
poll_in_simul_body() { h_audio poll_in_simul }

atf_test_case kqueue_mode_RDONLY_READ
kqueue_mode_RDONLY_READ_head() { }
kqueue_mode_RDONLY_READ_body() { h_audio kqueue_mode_RDONLY_READ }

atf_test_case kqueue_mode_RDONLY_WRITE
kqueue_mode_RDONLY_WRITE_head() { }
kqueue_mode_RDONLY_WRITE_body() { h_audio kqueue_mode_RDONLY_WRITE }

atf_test_case kqueue_mode_WRONLY_READ
kqueue_mode_WRONLY_READ_head() { }
kqueue_mode_WRONLY_READ_body() { h_audio kqueue_mode_WRONLY_READ }

atf_test_case kqueue_mode_WRONLY_WRITE
kqueue_mode_WRONLY_WRITE_head() { }
kqueue_mode_WRONLY_WRITE_body() { h_audio kqueue_mode_WRONLY_WRITE }

atf_test_case kqueue_mode_RDWR_READ
kqueue_mode_RDWR_READ_head() { }
kqueue_mode_RDWR_READ_body() { h_audio kqueue_mode_RDWR_READ }

atf_test_case kqueue_mode_RDWR_WRITE
kqueue_mode_RDWR_WRITE_head() { }
kqueue_mode_RDWR_WRITE_body() { h_audio kqueue_mode_RDWR_WRITE }

atf_test_case kqueue_empty
kqueue_empty_head() { }
kqueue_empty_body() { h_audio kqueue_empty }

atf_test_case kqueue_full
kqueue_full_head() { }
kqueue_full_body() { h_audio kqueue_full }

atf_test_case kqueue_hiwat
kqueue_hiwat_head() { }
kqueue_hiwat_body() { h_audio kqueue_hiwat }

atf_test_case kqueue_unpause
kqueue_unpause_head() { }
kqueue_unpause_body() { h_audio kqueue_unpause }

atf_test_case kqueue_simul
kqueue_simul_head() { }
kqueue_simul_body() { h_audio kqueue_simul }

atf_init_test_cases() {
	atf_add_test_case open_mode_RDONLY
	atf_add_test_case open_mode_WRONLY
	atf_add_test_case open_mode_RDWR
	atf_add_test_case open_audio_RDONLY
	atf_add_test_case open_audio_WRONLY
	atf_add_test_case open_audio_RDWR
	atf_add_test_case open_sound_RDONLY
	atf_add_test_case open_sound_WRONLY
	atf_add_test_case open_sound_RDWR
	atf_add_test_case open_sound_sticky
	atf_add_test_case open_simul_RDONLY_RDONLY
	atf_add_test_case open_simul_RDONLY_WRONLY
	atf_add_test_case open_simul_RDONLY_RDWR
	atf_add_test_case open_simul_WRONLY_RDONLY
	atf_add_test_case open_simul_WRONLY_WRONLY
	atf_add_test_case open_simul_WRONLY_RDWR
	atf_add_test_case open_simul_RDWR_RDONLY
	atf_add_test_case open_simul_RDWR_WRONLY
	atf_add_test_case open_simul_RDWR_RDWR
	atf_add_test_case open_multiuser_0
	atf_add_test_case open_multiuser_1
	atf_add_test_case write_PLAY_ALL
	atf_add_test_case write_PLAY
	atf_add_test_case read
	atf_add_test_case rept_write
	atf_add_test_case rept_read
	atf_add_test_case rdwr_fallback_RDONLY
	atf_add_test_case rdwr_fallback_WRONLY
	atf_add_test_case rdwr_fallback_RDWR
	atf_add_test_case rdwr_two_RDONLY_RDONLY
	atf_add_test_case rdwr_two_RDONLY_WRONLY
	atf_add_test_case rdwr_two_RDONLY_RDWR
	atf_add_test_case rdwr_two_WRONLY_RDONLY
	atf_add_test_case rdwr_two_WRONLY_WRONLY
	atf_add_test_case rdwr_two_WRONLY_RDWR
	atf_add_test_case rdwr_two_RDWR_RDONLY
	atf_add_test_case rdwr_two_RDWR_WRONLY
	atf_add_test_case rdwr_two_RDWR_RDWR
	atf_add_test_case rdwr_simul
	atf_add_test_case drain_incomplete
	atf_add_test_case drain_pause
	atf_add_test_case drain_onrec
	atf_add_test_case mmap_mode_RDONLY_NONE
	atf_add_test_case mmap_mode_RDONLY_READ
	atf_add_test_case mmap_mode_RDONLY_WRITE
	atf_add_test_case mmap_mode_RDONLY_READWRITE
	atf_add_test_case mmap_mode_WRONLY_NONE
	atf_add_test_case mmap_mode_WRONLY_READ
	atf_add_test_case mmap_mode_WRONLY_WRITE
	atf_add_test_case mmap_mode_WRONLY_READWRITE
	atf_add_test_case mmap_mode_RDWR_NONE
	atf_add_test_case mmap_mode_RDWR_READ
	atf_add_test_case mmap_mode_RDWR_WRITE
	atf_add_test_case mmap_mode_RDWR_READWRITE
	atf_add_test_case mmap_len
	atf_add_test_case mmap_twice
	atf_add_test_case mmap_multi
	atf_add_test_case poll_mode_RDONLY_IN
	atf_add_test_case poll_mode_RDONLY_OUT
	atf_add_test_case poll_mode_RDONLY_INOUT
	atf_add_test_case poll_mode_WRONLY_IN
	atf_add_test_case poll_mode_WRONLY_OUT
	atf_add_test_case poll_mode_WRONLY_INOUT
	atf_add_test_case poll_mode_RDWR_IN
	atf_add_test_case poll_mode_RDWR_OUT
	atf_add_test_case poll_mode_RDWR_INOUT
	atf_add_test_case poll_out_empty
	atf_add_test_case poll_out_full
	atf_add_test_case poll_out_hiwat
	atf_add_test_case poll_out_unpause
	atf_add_test_case poll_out_simul
	atf_add_test_case poll_in_simul
	atf_add_test_case kqueue_mode_RDONLY_READ
	atf_add_test_case kqueue_mode_RDONLY_WRITE
	atf_add_test_case kqueue_mode_WRONLY_READ
	atf_add_test_case kqueue_mode_WRONLY_WRITE
	atf_add_test_case kqueue_mode_RDWR_READ
	atf_add_test_case kqueue_mode_RDWR_WRITE
	atf_add_test_case kqueue_empty
	atf_add_test_case kqueue_full
	atf_add_test_case kqueue_hiwat
	atf_add_test_case kqueue_unpause
	atf_add_test_case kqueue_simul
}
